import { REFINED_STANDARDS } from "./refined-standards-data";

export interface TRIAHReference {
  id: string;
  title: string;
  shortName: string;
  issuer: string;
  type: "federal" | "international" | "state" | "standards_body" | "consensus" | "academic";
  tier: "mandatory" | "preferred" | "optional";
  url: string;
  description: string;
  standardIds: string[];
  factorIds: string[];
}

export const TRIAH_REFERENCES: TRIAHReference[] = [
  {
    id: "REF-FDA-SAMD",
    title: "FDA Software as a Medical Device (SaMD) Guidance",
    shortName: "FDA SaMD",
    issuer: "U.S. Food & Drug Administration",
    type: "federal",
    tier: "mandatory",
    url: "https://www.fda.gov/medical-devices/software-medical-device-samd",
    description: "FDA guidance defining Software as a Medical Device classification, regulatory pathways (510(k), De Novo, PMA), and oversight framework for AI/ML-based medical software. Governs regulatory clearance and intended use requirements.",
    standardIds: ["S1", "S2", "S4", "S6", "S8"],
    factorIds: [
      "S1.E1.F1", "S1.E1.F2", "S1.E1.F4",
      "S2.E4.F1",
      "S4.E1.F1",
      "S6.E1.F1", "S6.E2.F1",
      "S8.E4.F1",
    ],
  },
  {
    id: "REF-FDA-GMLP",
    title: "Good Machine Learning Practice for Medical Device Development (2021)",
    shortName: "FDA GMLP",
    issuer: "U.S. Food & Drug Administration",
    type: "federal",
    tier: "mandatory",
    url: "https://www.fda.gov/medical-devices/software-medical-device-samd/good-machine-learning-practice-medical-device-development-guiding-principles",
    description: "Ten guiding principles for developing AI/ML-based SaMD, covering data management, model training, validation, transparency, and post-deployment monitoring. Co-authored by FDA, Health Canada, and MHRA.",
    standardIds: ["S1", "S4", "S6", "S7"],
    factorIds: [
      "S1.E5.F1", "S1.E5.F3", "S1.E6.F1",
      "S4.E3.F1", "S4.E3.F2",
      "S6.E1.F1", "S6.E2.F1", "S6.E4.F1", "S6.E4.F2",
      "S7.E1.F1", "S7.E2.F1", "S7.E3.F5",
    ],
  },
  {
    id: "REF-FDA-CHANGE",
    title: "FDA Predetermined Change Control Plan (PCCP) Guidance",
    shortName: "FDA PCCP",
    issuer: "U.S. Food & Drug Administration",
    type: "federal",
    tier: "mandatory",
    url: "https://www.fda.gov/media/122535/download",
    description: "Regulatory framework for managing AI/ML model changes without requiring new submissions for pre-specified, pre-approved modifications. Defines scope, change categories, and documentation requirements for model updates.",
    standardIds: ["S1", "S8"],
    factorIds: [
      "S1.E1.F3",
      "S6.E4.F2",
      "S8.E4.F1", "S8.E4.F2",
    ],
  },
  {
    id: "REF-FDA-CYBER",
    title: "FDA Cybersecurity in Medical Devices Guidance (2023)",
    shortName: "FDA Cybersecurity",
    issuer: "U.S. Food & Drug Administration",
    type: "federal",
    tier: "mandatory",
    url: "https://www.fda.gov/regulatory-information/search-fda-guidance-documents/cybersecurity-medical-devices",
    description: "Mandatory cybersecurity requirements for medical devices including SaMD: secure design, vulnerability management, software bill of materials (SBOM), and coordinated disclosure. Establishes minimum cybersecurity expectations for market authorization.",
    standardIds: ["S1", "S2"],
    factorIds: [
      "S1.E4.F1", "S1.E4.F2", "S1.E4.F3",
      "S2.E4.F1",
    ],
  },
  {
    id: "REF-HIPAA-PRIVACY",
    title: "HIPAA Privacy Rule",
    shortName: "HIPAA Privacy",
    issuer: "HHS Office for Civil Rights",
    type: "federal",
    tier: "mandatory",
    url: "https://www.hhs.gov/hipaa/for-professionals/privacy/index.html",
    description: "Federal standards protecting the privacy of individuals' medical records and health information. Governs use, disclosure, and safeguarding of Protected Health Information (PHI) by covered entities and business associates.",
    standardIds: ["S1", "S2", "S5"],
    factorIds: [
      "S1.E3.F1", "S1.E3.F2", "S1.E3.F3", "S1.E3.F4",
      "S5.E1.F3",
    ],
  },
  {
    id: "REF-HIPAA-SECURITY",
    title: "HIPAA Security Rule",
    shortName: "HIPAA Security",
    issuer: "HHS Office for Civil Rights",
    type: "federal",
    tier: "mandatory",
    url: "https://www.hhs.gov/hipaa/for-professionals/security/index.html",
    description: "Federal standards for administrative, physical, and technical safeguards to protect electronic Protected Health Information (ePHI). Mandates encryption, access controls, audit logging, and breach notification procedures.",
    standardIds: ["S1", "S2"],
    factorIds: [
      "S1.E3.F1", "S1.E3.F3",
      "S1.E4.F1", "S1.E4.F3",
    ],
  },
  {
    id: "REF-ONC-HTI1",
    title: "ONC HTI-1 Final Rule (Health Data, Technology & Interoperability)",
    shortName: "ONC HTI-1",
    issuer: "Office of the National Coordinator for Health IT (ONC)",
    type: "federal",
    tier: "mandatory",
    url: "https://healthit.gov/regulations/hti-rules/hti-1-final-rule/",
    description: "Implements information blocking prohibitions, AI/ML algorithm transparency requirements (§170.315(g)(11)), and updated USCDI v3 standards. Requires transparency about AI predictive models used in EHR-certified systems.",
    standardIds: ["S1", "S2", "S3"],
    factorIds: [
      "S1.E2.F3",
      "S2.E1.F1", "S2.E2.F1", "S2.E3.F1", "S2.E3.F4", "S2.E6.F2",
      "S3.E1.F4", "S3.E5.F1",
    ],
  },
  {
    id: "REF-ONC-HTI5",
    title: "ONC HTI-5 Proposed Rule",
    shortName: "ONC HTI-5",
    issuer: "Office of the National Coordinator for Health IT (ONC)",
    type: "federal",
    tier: "preferred",
    url: "https://healthit.gov/regulations/hti-rules/hti-5-proposed-rule/",
    description: "Proposed deregulatory updates to ONC Health IT Certification including clarification that autonomous AI is covered under health information access and exchange requirements. Introduces Standards Version Advancement Process (SVAP) for faster FHIR adoption.",
    standardIds: ["S2"],
    factorIds: [
      "S2.E1.F1", "S2.E3.F3",
    ],
  },
  {
    id: "REF-CMS",
    title: "CMS Conditions of Participation & Interoperability Rules",
    shortName: "CMS",
    issuer: "Centers for Medicare & Medicaid Services",
    type: "federal",
    tier: "mandatory",
    url: "https://www.cms.gov/regulations-and-guidance",
    description: "CMS requirements governing healthcare AI in Medicare/Medicaid contexts, including interoperability mandates (CMS-0057-F), prior authorization transparency, and operational compliance requirements for healthcare organizations.",
    standardIds: ["S1", "S2"],
    factorIds: [
      "S1.E2.F1", "S1.E2.F3",
      "S2.E1.F1", "S2.E3.F1", "S2.E3.F4",
    ],
  },
  {
    id: "REF-NIST-AIRMF",
    title: "NIST AI Risk Management Framework (AI RMF 1.0)",
    shortName: "NIST AI RMF",
    issuer: "National Institute of Standards & Technology",
    type: "federal",
    tier: "mandatory",
    url: "https://www.nist.gov/itl/ai-risk-management-framework",
    description: "Comprehensive voluntary framework for identifying, assessing, and managing AI risks across the lifecycle. Provides GOVERN, MAP, MEASURE, and MANAGE functions for trustworthy AI. Referenced by FDA as foundational for SaMD risk management.",
    standardIds: ["S1", "S5", "S6", "S8"],
    factorIds: [
      "S1.E1.F3", "S1.E5.F1", "S1.E5.F2",
      "S5.E3.F1", "S5.E3.F2", "S5.E4.F1",
      "S6.E3.F1", "S6.E4.F1",
      "S8.E1.F1", "S8.E1.F3",
    ],
  },
  {
    id: "REF-NIST-CSF",
    title: "NIST Cybersecurity Framework (CSF 2.0)",
    shortName: "NIST CSF",
    issuer: "National Institute of Standards & Technology",
    type: "federal",
    tier: "mandatory",
    url: "https://www.nist.gov/cyberframework",
    description: "Framework for improving critical infrastructure cybersecurity with IDENTIFY, PROTECT, DETECT, RESPOND, and RECOVER functions. Widely adopted by healthcare organizations for cybersecurity program management and compliance.",
    standardIds: ["S1"],
    factorIds: [
      "S1.E4.F1", "S1.E4.F2", "S1.E4.F3",
    ],
  },
  {
    id: "REF-USCDI",
    title: "United States Core Data for Interoperability (USCDI v3)",
    shortName: "USCDI v3",
    issuer: "ONC",
    type: "federal",
    tier: "mandatory",
    url: "https://www.healthit.gov/isa/united-states-core-data-interoperability-uscdi",
    description: "Standardized set of health data classes and elements required for nationwide interoperable health information exchange. As of January 2026, certified health IT must support USCDI v3, which includes SDOH, immunizations, and expanded clinical data.",
    standardIds: ["S2"],
    factorIds: [
      "S2.E1.F1", "S2.E1.F4",
    ],
  },
  {
    id: "REF-EU-AI-ACT",
    title: "EU Artificial Intelligence Act (2024)",
    shortName: "EU AI Act",
    issuer: "European Union",
    type: "international",
    tier: "mandatory",
    url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689",
    description: "Landmark EU regulation establishing risk-based framework for AI systems. High-risk AI systems (including medical AI) must meet requirements for human oversight (Article 14), transparency (Article 13), and technical documentation. Directly governs EU market access.",
    standardIds: ["S1", "S3", "S7"],
    factorIds: [
      "S1.E1.F1",
      "S3.E1.F4", "S3.E2.F3", "S3.E5.F1",
      "S7.E1.F1", "S7.E1.F3", "S7.E3.F1", "S7.E3.F5",
      "S7.E4.F2", "S7.E7.F1",
    ],
  },
  {
    id: "REF-ISO-14971",
    title: "ISO 14971:2019 — Medical Devices Risk Management",
    shortName: "ISO 14971",
    issuer: "International Organization for Standardization",
    type: "standards_body",
    tier: "mandatory",
    url: "https://www.iso.org/standard/72704.html",
    description: "International standard for risk management of medical devices including SaMD. Requires systematic hazard identification, risk estimation, evaluation, and control. Mandated by FDA 21 CFR 820, EU MDR, and referenced by ISO/IEC 62304.",
    standardIds: ["S1", "S6"],
    factorIds: [
      "S1.E5.F1", "S1.E5.F2", "S1.E5.F3",
      "S4.E5.F2",
    ],
  },
  {
    id: "REF-IEC-62304",
    title: "IEC 62304:2006+AMD1:2015 — Medical Device Software Lifecycle",
    shortName: "IEC 62304",
    issuer: "International Electrotechnical Commission",
    type: "standards_body",
    tier: "mandatory",
    url: "https://www.iso.org/standard/38421.html",
    description: "Standard for medical device software development lifecycle processes covering software development planning, requirements, architecture, testing, and maintenance. Required for FDA 510(k) and EU MDR software submissions.",
    standardIds: ["S1", "S2", "S6", "S8"],
    factorIds: [
      "S1.E2.F1", "S1.E2.F2",
      "S2.E4.F1",
      "S6.E2.F2",
      "S8.E4.F1", "S8.E4.F2",
    ],
  },
  {
    id: "REF-IEC-62366",
    title: "IEC 62366-1:2015 — Usability Engineering for Medical Devices",
    shortName: "IEC 62366",
    issuer: "International Electrotechnical Commission",
    type: "standards_body",
    tier: "preferred",
    url: "https://www.iso.org/standard/63179.html",
    description: "Standard for applying usability engineering to medical devices to reduce use-related risks. Requires summative usability evaluation with representative users, task analysis, and use-related risk analysis.",
    standardIds: ["S1", "S7"],
    factorIds: [
      "S1.E5.F1",
      "S7.E6.F1", "S7.E6.F4",
    ],
  },
  {
    id: "REF-IMDRF-SAMD",
    title: "IMDRF SaMD Clinical Evaluation Guidance (2019)",
    shortName: "IMDRF SaMD",
    issuer: "International Medical Device Regulators Forum",
    type: "international",
    tier: "mandatory",
    url: "https://www.imdrf.org/documents/software-medical-device-samd-clinical-evaluation",
    description: "International guidance for the clinical evaluation of SaMD, defining valid clinical association, analytical validation, and clinical validation as the three-part framework for demonstrating clinical evidence.",
    standardIds: ["S4", "S6"],
    factorIds: [
      "S4.E1.F1", "S4.E2.F1",
      "S6.E1.F1", "S6.E2.F1",
    ],
  },
  {
    id: "REF-MHRA",
    title: "MHRA Software and AI as a Medical Device Change Programme (2022)",
    shortName: "MHRA AI Programme",
    issuer: "Medicines and Healthcare Products Regulatory Agency (UK)",
    type: "international",
    tier: "preferred",
    url: "https://www.gov.uk/government/publications/software-and-ai-as-a-medical-device-change-programme",
    description: "UK regulatory programme updating the regulatory framework for software and AI as medical devices. Introduces manufacturer registration, total product lifecycle approach, and real-world evidence requirements.",
    standardIds: ["S6"],
    factorIds: [
      "S6.E2.F1", "S6.E5.F1",
    ],
  },
  {
    id: "REF-EMA",
    title: "EMA Reflection Paper on AI in Medicinal Product Lifecycle (2023)",
    shortName: "EMA AI Paper",
    issuer: "European Medicines Agency",
    type: "international",
    tier: "preferred",
    url: "https://www.ema.europa.eu/",
    description: "EMA guidance on use of AI and machine learning in medicinal product development and regulatory submissions. Addresses data quality, model validation, explainability, and ongoing monitoring requirements.",
    standardIds: ["S6"],
    factorIds: [
      "S6.E2.F1", "S6.E2.F3",
    ],
  },
  {
    id: "REF-HL7-FHIR",
    title: "HL7 Fast Healthcare Interoperability Resources (FHIR R5+)",
    shortName: "HL7 FHIR",
    issuer: "Health Level Seven International",
    type: "standards_body",
    tier: "mandatory",
    url: "https://hl7.org/fhir/",
    description: "The primary API standard for real-time healthcare data exchange using RESTful APIs with JSON/XML. Mandated by ONC HTI-1 for EHR interoperability. Includes SMART on FHIR for secure app authorization and Bulk Data API for population-level access.",
    standardIds: ["S2"],
    factorIds: [
      "S2.E1.F1", "S2.E3.F1", "S2.E3.F3", "S2.E3.F4",
    ],
  },
  {
    id: "REF-DICOM",
    title: "DICOM Standard (Digital Imaging and Communications in Medicine)",
    shortName: "DICOM",
    issuer: "NEMA / DICOM Standards Committee",
    type: "standards_body",
    tier: "mandatory",
    url: "https://www.dicomstandard.org/current",
    description: "Global standard for managing, storing, printing, and transmitting medical imaging information. Required for imaging AI products. Includes IHE AIR profile for AI-generated imaging analysis results storage and retrieval.",
    standardIds: ["S2"],
    factorIds: [
      "S2.E1.F2",
    ],
  },
  {
    id: "REF-HL7-CCDA",
    title: "HL7 C-CDA (Consolidated Clinical Document Architecture)",
    shortName: "HL7 C-CDA",
    issuer: "Health Level Seven International",
    type: "standards_body",
    tier: "preferred",
    url: "https://hl7.org/cda/us/ccda/history.html",
    description: "US implementation guide for CDA providing standard templates for electronic health records exchange (Continuity of Care Documents, discharge summaries, referrals). Supports care coordination and AI-driven clinical document analysis.",
    standardIds: ["S2"],
    factorIds: [
      "S2.E1.F3",
    ],
  },
  {
    id: "REF-SMART-FHIR",
    title: "SMART on FHIR (Substitutable Medical Applications & Reusable Technologies)",
    shortName: "SMART on FHIR",
    issuer: "Health Level Seven International",
    type: "standards_body",
    tier: "mandatory",
    url: "https://smarthealthit.org/smart-on-fhir-api",
    description: "Open standard framework allowing third-party AI applications to securely access EHR data using OAuth 2.0 and OpenID Connect. Enables seamless AI app integration within EHR environments across different vendor platforms.",
    standardIds: ["S2"],
    factorIds: [
      "S2.E1.F1", "S2.E3.F3",
    ],
  },
  {
    id: "REF-ISO-MAPQUAL",
    title: "ISO/TS 21564:2025 — Terminology Mapping Quality (MapQual)",
    shortName: "ISO MapQual",
    issuer: "International Organization for Standardization",
    type: "standards_body",
    tier: "optional",
    url: "https://iso.org/standard/86417.html",
    description: "Technical specification for evaluating quality of mappings between healthcare terminology resources (SNOMED CT, LOINC, ICD). Establishes utility, completeness, and fitness-for-purpose metrics for terminology interoperability.",
    standardIds: ["S2"],
    factorIds: [
      "S2.E1.F4",
    ],
  },
  {
    id: "REF-WHO-AI",
    title: "WHO Ethics and Governance of AI for Health (2021)",
    shortName: "WHO AI Ethics",
    issuer: "World Health Organization",
    type: "consensus",
    tier: "preferred",
    url: "https://www.who.int/publications/i/item/9789240029200",
    description: "WHO guidance establishing six ethical principles for AI in health: protecting autonomy, promoting wellbeing, ensuring transparency, fostering accountability, ensuring equity and inclusivity, and promoting sustainability. Widely referenced by national AI frameworks.",
    standardIds: ["S5", "S6", "S7"],
    factorIds: [
      "S5.E6.F2",
      "S6.E2.F1",
      "S7.E1.F3", "S7.E3.F1", "S7.E3.F5",
    ],
  },
  {
    id: "REF-OECD-AI",
    title: "OECD AI Principles (2019, updated 2024)",
    shortName: "OECD AI",
    issuer: "Organisation for Economic Co-operation and Development",
    type: "consensus",
    tier: "preferred",
    url: "https://www.oecd.org/digital/artificial-intelligence/",
    description: "First intergovernmental standards on AI, adopted by 42+ countries. Establishes five principles: inclusive growth, human-centered values, transparency, robustness/security, and accountability. Foundation for many national AI governance frameworks.",
    standardIds: ["S5", "S7"],
    factorIds: [
      "S5.E1.F4",
      "S7.E2.F3", "S7.E3.F6",
    ],
  },
  {
    id: "REF-UNESCO-AI",
    title: "UNESCO Recommendation on the Ethics of AI (2021)",
    shortName: "UNESCO AI Ethics",
    issuer: "United Nations Educational, Scientific and Cultural Organization",
    type: "consensus",
    tier: "preferred",
    url: "https://www.unesco.org/en/artificial-intelligence/recommendation-ethics",
    description: "First global standard-setting instrument on AI ethics adopted by 193 UNESCO member states. Covers human rights, dignity, diversity, environment, AI lifecycle governance, privacy, and oversight with concrete policy action recommendations.",
    standardIds: ["S5", "S7"],
    factorIds: [
      "S5.E6.F2",
      "S7.E1.F3",
    ],
  },
  {
    id: "REF-CHAI",
    title: "CHAI Blueprint for Trustworthy AI Implementation (2023)",
    shortName: "CHAI Blueprint",
    issuer: "Coalition for Health AI",
    type: "consensus",
    tier: "preferred",
    url: "https://www.coalitionforhealthai.org/",
    description: "US healthcare-specific AI governance framework from CHAI covering model cards, transparency, bias assessment, human oversight, and assurance standards. Model card template widely adopted for healthcare AI transparency reporting.",
    standardIds: ["S3", "S7", "S8"],
    factorIds: [
      "S3.E1.F4", "S3.E5.F1",
      "S7.E3.F1", "S7.E4.F2",
      "S8.E1.F1",
    ],
  },
  {
    id: "REF-JOINT-COMMISSION",
    title: "Joint Commission — Safe and Trustworthy AI (2024)",
    shortName: "Joint Commission AI",
    issuer: "The Joint Commission",
    type: "consensus",
    tier: "preferred",
    url: "https://www.jointcommission.org/",
    description: "Joint Commission guidance for healthcare organizations deploying AI systems, addressing governance, clinical integration, oversight, staff competency, and ongoing monitoring. Sets expectations for accredited healthcare facilities using AI.",
    standardIds: ["S7", "S8"],
    factorIds: [
      "S7.E3.F2", "S7.E4.F1",
      "S8.E1.F1", "S8.E3.F1",
    ],
  },
  {
    id: "REF-FUTURE-AI",
    title: "FUTURE-AI International Consensus Guideline (2024)",
    shortName: "FUTURE-AI",
    issuer: "FUTURE-AI Consortium",
    type: "consensus",
    tier: "preferred",
    url: "https://future-ai.eu/",
    description: "International consensus guidelines for trustworthy and deployable AI in healthcare, covering Fairness, Universality, Traceability, Usability, Robustness, Explainability, and training (acronym FUTURE-AI). Developed by 100+ institutions across 51 countries.",
    standardIds: ["S2", "S7"],
    factorIds: [
      "S2.E4.F3",
      "S7.E2.F1", "S7.E6.F3",
    ],
  },
  {
    id: "REF-ICMR",
    title: "ICMR Ethical Guidelines for Application of AI in Biomedical Research and Healthcare (2023)",
    shortName: "ICMR AI Ethics",
    issuer: "Indian Council of Medical Research",
    type: "consensus",
    tier: "preferred",
    url: "https://main.icmr.nic.in/",
    description: "India's national guidelines for ethical AI in healthcare emphasizing that clinicians retain final responsibility for AI-assisted decisions, with requirements for transparency, accountability, and human oversight.",
    standardIds: ["S5", "S7"],
    factorIds: [
      "S5.E6.F1",
      "S7.E1.F3", "S7.E3.F5",
    ],
  },
  {
    id: "REF-NICE",
    title: "NICE Evidence Standards Framework for Digital Health Technologies (2022)",
    shortName: "NICE DHT",
    issuer: "National Institute for Health and Care Excellence (UK)",
    type: "consensus",
    tier: "preferred",
    url: "https://www.nice.org.uk/about/what-we-do/our-programmes/evidence-standards-framework-for-digital-health-technologies",
    description: "UK standards defining evidence requirements for digital health technologies used in NHS care. Specifies clinical evidence tiers, data quality standards, and real-world evaluation expectations for AI-based diagnostic and decision support tools.",
    standardIds: ["S4", "S6"],
    factorIds: [
      "S4.E1.F1", "S4.E2.F1",
      "S6.E1.F1", "S6.E2.F1",
    ],
  },
  {
    id: "REF-SPIRIT-CONSORT-AI",
    title: "SPIRIT-AI & CONSORT-AI Reporting Guidelines (2020)",
    shortName: "SPIRIT/CONSORT-AI",
    issuer: "SPIRIT-AI & CONSORT-AI Working Group",
    type: "academic",
    tier: "preferred",
    url: "https://www.nature.com/articles/s41591-020-1034-x",
    description: "Standard reporting guidelines for clinical trial protocols (SPIRIT-AI) and results (CONSORT-AI) involving AI interventions. Ensures complete and transparent reporting of AI-specific design decisions, training data, model performance, and human-AI interaction.",
    standardIds: ["S4", "S6"],
    factorIds: [
      "S4.E1.F1", "S4.E2.F3",
      "S6.E2.F1",
    ],
  },
  {
    id: "REF-TRIPOD-AI",
    title: "TRIPOD+AI Reporting Framework (2023)",
    shortName: "TRIPOD+AI",
    issuer: "TRIPOD Working Group / BMJ",
    type: "academic",
    tier: "preferred",
    url: "https://www.bmj.com/content/385/bmj-2023-078378",
    description: "Extension of TRIPOD guidelines for transparent reporting of multivariable prediction models incorporating AI/ML. Covers study design, data preparation, model development, performance evaluation, and clinical utility reporting.",
    standardIds: ["S4", "S6"],
    factorIds: [
      "S4.E2.F3",
      "S6.E2.F1", "S6.E2.F2", "S6.E2.F3",
    ],
  },
  {
    id: "REF-TX-HB149",
    title: "Texas HB 149 — Relating to the Use of AI in Healthcare",
    shortName: "Texas HB 149",
    issuer: "Texas Legislature (89th Session)",
    type: "state",
    tier: "mandatory",
    url: "https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB149",
    description: "Texas state legislation requiring healthcare entities using AI to disclose AI involvement to patients, maintain human oversight for clinical decisions, and establish accountability frameworks. Part of emerging state-level AI governance landscape.",
    standardIds: ["S1", "S3", "S7"],
    factorIds: [
      "S1.E1.F2",
      "S3.E2.F3",
      "S7.E1.F3", "S7.E7.F2",
    ],
  },
  {
    id: "REF-TX-SB1188",
    title: "Texas SB 1188 — Relating to Standards for AI in Healthcare Settings",
    shortName: "Texas SB 1188",
    issuer: "Texas Legislature (89th Session)",
    type: "state",
    tier: "mandatory",
    url: "https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=SB1188",
    description: "Companion Texas legislation establishing standards for responsible AI deployment in healthcare settings, including provisions for clinician authority over AI recommendations and patient notification requirements.",
    standardIds: ["S7"],
    factorIds: [
      "S7.E1.F3", "S7.E7.F1",
    ],
  },
  {
    id: "REF-IEEE-2807",
    title: "IEEE P2807 — Framework for AI in Healthcare",
    shortName: "IEEE 2807",
    issuer: "Institute of Electrical and Electronics Engineers",
    type: "standards_body",
    tier: "optional",
    url: "https://standards.ieee.org/ieee/2807/",
    description: "IEEE standards framework for AI deployment in healthcare environments, addressing technical requirements for scalability, compute footprint, horizontal scaling, and healthcare-specific infrastructure considerations.",
    standardIds: ["S2", "S6"],
    factorIds: [
      "S2.E4.F3",
      "S6.E5.F2",
    ],
  },
  {
    id: "REF-ISO-27001",
    title: "ISO/IEC 27001:2022 — Information Security Management Systems",
    shortName: "ISO 27001",
    issuer: "International Organization for Standardization / IEC",
    type: "standards_body",
    tier: "preferred",
    url: "https://www.iso.org/standard/27001",
    description: "International standard for information security management systems (ISMS). Provides systematic approach for managing sensitive company information, including risk assessment, security controls, and certification audit requirements relevant to healthcare AI data security.",
    standardIds: ["S1", "S2"],
    factorIds: [
      "S1.E4.F1", "S1.E4.F3",
      "S2.E3.F3",
    ],
  },
];

export function getReferencesForFactor(factorId: string): TRIAHReference[] {
  return TRIAH_REFERENCES.filter(ref => ref.factorIds.includes(factorId));
}

export function getReferencesForStandard(standardId: string): TRIAHReference[] {
  return TRIAH_REFERENCES.filter(ref => ref.standardIds.includes(standardId));
}

export function getReferencesByTier(tier: "mandatory" | "preferred" | "optional"): TRIAHReference[] {
  return TRIAH_REFERENCES.filter(ref => ref.tier === tier);
}

export function isTRIAHIP(factorId: string): boolean {
  for (const std of REFINED_STANDARDS) {
    for (const el of std.elements) {
      const factor = el.factors.find(f => f.id === factorId);
      if (factor) return !(factor.referenceIds?.length);
    }
  }
  return true;
}

export function getTRIAHIPFactors(allFactorIds: string[]): string[] {
  return allFactorIds.filter(id => isTRIAHIP(id));
}
